### ISSUE TITLE
Failed to Build

### ISSUE THREAD

**Issue by feichai2004** [yanii/kitti-pcl#1]
Hi,

I try to build the source code and found the following error message. Do you have any ideal?

/home/hengfuil/code/kitti-pcl/src/kittitrackletextract.cpp: In function ‘int main(int, char*_)’:
/home/hengfuil/code/kitti-pcl/src/kittitrackletextract.cpp:67:2: error: ‘sensor_msgs’ has not been declared
  sensor_msgs::PointCloud2 blob;
  ^
/home/hengfuil/code/kitti-pcl/src/kittitrackletextract.cpp:67:27: error: expected ‘;’ before ‘blob’
  sensor_msgs::PointCloud2 blob;
                           ^
/home/hengfuil/code/kitti-pcl/src/kittitrackletextract.cpp:68:40: error: ‘blob’ was not declared in this scope
  pcl::io::loadPCDFile (infile.c_str(), blob);
                                        ^
/home/hengfuil/code/kitti-pcl/src/kittitrackletextract.cpp:72:2: error: ‘fromROSMsg’ is not a member of ‘pcl’
  pcl::fromROSMsg (blob, *cloud);
  ^
make[2]: *_\* [src/CMakeFiles/kittitrackletextract.dir/kittitrackletextract.cpp.o] Error 1
make[2]: Leaving directory `/home/hengfuil/code/kitti-pcl'
make[1]: *** [src/CMakeFiles/kittitrackletextract.dir/all] Error 2
make[1]: Leaving directory`/home/hengfuil/code/kitti-pcl'
make: **\* [all] Error 2

**Comment by MarkMuth** [comment]
Well,

obviously ‘sensor_msgs’ has not been declared. Looks like you have no 
compatible version of ROS/PCL installed.

Cheers,
Mark

**Comment by feichai2004** [comment]
Yes, it is a compatible issues. I fixed the problem by following the recommendation.  
https://github.com/PointCloudLibrary/pcl/wiki/Remove-ROS

**Comment by gyubeomim** [comment]
@feichai2004 
thanks, 
after running remove_ros_3rdparty.bash in the page you recommended, it worked for me
